// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using URLShortener.DAL.Context;

#nullable disable

namespace URLShortener.DAL.Migrations
{
    [DbContext(typeof(URLShortenerDbContext))]
    [Migration("20240527023637_GenerateData")]
    partial class GenerateData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("URLShortener.DAL.Entities.UrlAdress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortenedUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UrlAdresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70c755bd-f96b-4a82-8a0a-a29fbba009f4"),
                            CreatedDate = new DateTime(2024, 5, 27, 5, 36, 35, 988, DateTimeKind.Local).AddTicks(7008),
                            OriginalUrl = "OriginalUrl/justForTest",
                            ShortenedUrl = "ShortenedUrl/justForTest",
                            UserId = new Guid("9b4673fb-20c2-4341-9a36-a3cfaa22878b")
                        },
                        new
                        {
                            Id = new Guid("78f30a41-a1da-4c73-b237-7879864d854b"),
                            CreatedDate = new DateTime(2024, 5, 27, 5, 36, 35, 992, DateTimeKind.Local).AddTicks(5062),
                            OriginalUrl = "OriginalUrl/justForTest",
                            ShortenedUrl = "ShortenedUrl/justForTest",
                            UserId = new Guid("9b4673fb-20c2-4341-9a36-a3cfaa22878b")
                        },
                        new
                        {
                            Id = new Guid("8a7e0782-8fb7-4371-986d-b3110255bc59"),
                            CreatedDate = new DateTime(2024, 5, 27, 5, 36, 35, 992, DateTimeKind.Local).AddTicks(5100),
                            OriginalUrl = "OriginalUrl/justForTest",
                            ShortenedUrl = "ShortenedUrl/justForTest",
                            UserId = new Guid("747a1720-4ca3-43e2-93fa-becc860589dc")
                        },
                        new
                        {
                            Id = new Guid("50a89e67-967e-4d98-916e-c53378a48a6b"),
                            CreatedDate = new DateTime(2024, 5, 27, 5, 36, 35, 992, DateTimeKind.Local).AddTicks(5105),
                            OriginalUrl = "OriginalUrl/justForTest",
                            ShortenedUrl = "ShortenedUrl/justForTest",
                            UserId = new Guid("539ad3f7-7478-4b34-8a09-9509b6f4adfd")
                        });
                });

            modelBuilder.Entity("URLShortener.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b4673fb-20c2-4341-9a36-a3cfaa22878b"),
                            HashPassword = "r4A/IOyfd//CftSMJ0/HYQ==:57hdC+TEJMp1K0tT8g9idzFKhJShQa+s0kDt7EVaoMQ=",
                            IsAdmin = false,
                            Username = "test1"
                        },
                        new
                        {
                            Id = new Guid("747a1720-4ca3-43e2-93fa-becc860589dc"),
                            HashPassword = "r4A/IOyfd//CftSMJ0/HYQ==:57hdC+TEJMp1K0tT8g9idzFKhJShQa+s0kDt7EVaoMQ=",
                            IsAdmin = true,
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("539ad3f7-7478-4b34-8a09-9509b6f4adfd"),
                            HashPassword = "r4A/IOyfd//CftSMJ0/HYQ==:57hdC+TEJMp1K0tT8g9idzFKhJShQa+s0kDt7EVaoMQ=",
                            IsAdmin = false,
                            Username = "test2"
                        });
                });

            modelBuilder.Entity("URLShortener.DAL.Entities.UrlAdress", b =>
                {
                    b.HasOne("URLShortener.DAL.Entities.User", "CreatedBy")
                        .WithMany("UrlAdresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("URLShortener.DAL.Entities.User", b =>
                {
                    b.Navigation("UrlAdresses");
                });
#pragma warning restore 612, 618
        }
    }
}
